### ISSUE TITLE
QR codes should be resizable

### ISSUE THREAD

**Issue by florolf** [fxkr/chrome-qrcode-extension#2]
One should be able to increase the size of the generated QR code to make it easier to scan.

**Comment by fxkr** [comment]
I just tried that; it was pretty straightforward to implement, however:

* Chrome apparently has a hardcoded popup window size limit of 800x600, and if we get over that, we get scrollbars.
* There is no reason to use anything but the largest possible cell size that fits.
* Finding the largest possible cell size manually is tedious.
* The largest possible cell size depends on the QR code version (=> length of URL), so persistent cell sizes wouldn't be useful.

So now we automatically estimate the largest possible cell size (`(600px - space for UI) / number of modules)`) and go with that.
