### ISSUE TITLE
Upgrade to newest GOOG reqs to both avoid delisting and keep the extension working

### ISSUE THREAD

**Issue by no-identd** [fxkr/chrome-qrcode-extension#5]
@fxkr any chance of a minor update to the extension? The Chrome Extension Store already shows a warning about it. I guess you'd have to migrate to manifest V3 and to update some metadata in the store?

**Comment by fxkr** [comment]
I'd be happy to. Would you be able to submit a pull request with the necessary changes?

**Comment by fxkr** [comment]
Nevermind, I managed to make the required changes during my lunch break :-)

* Manifest
  * Update extension version
  * Update manifest version
  * Switch from "tabs" to "activeTab" permission
  * Switch from "browser_action" to "action" setting
* Code
  * Switch from chrome.tabs.getSelected to chrome.tabs.query
* Misc
  * Add required privacy policy page
  * Fill in new fields in Chrome Web Store submission page

I have submitted a new version (1.1.0) to the Chrome Web Store. It is now pending review by Google. I estimate it will take them between 30 minutes and 30 years to approve it.

Thank you very much for reminding me to do this! Appreciate it :heart:

**Comment by fxkr** [comment]
It appears the new version has been published successfully.

Thanks again!
